### ISSUE TITLE
Missing artefact jig:protocols:jar:qcon

### ISSUE THREAD

**Issue by tgk** [juxt/jig#19]
A dependency seems to be missing from HEAD

$ lein deps
Could not find artifact jig:protocols:jar:qcon in central (http://repo1.maven.org/maven2/)
Could not find artifact jig:protocols:jar:qcon in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.

**Comment by malcolmsparks** [comment]
The problem was that I tagged the jig repo with qcon, so jig thinks that
qcon is the version. Remove the tag from the jig repo first.

$ git tag -d qcon

**Comment by tgk** [comment]
Thanks! I ended up reverting to 2.0.0
