### ISSUE TITLE
jig.cljs/Builder should pass an environment to cljs.closure/build

### ISSUE THREAD

**Issue by ivan** [juxt/jig#4]
`(cljs.closure/build )` takes an optional third argument, a compiler environment holding compiler state.  Passing in the same environment repeatedly significantly speeds up CLJS builds (4000ms vs 400ms for :optimizations :whitespace and no :source-map).  lein-cljsbuild already passes in an environment.

This should be a `(cljs.env/default-compiler-env)`.  I don't know if I should be in the `jig.cljs/Builder` or in the `jig.cljs` namespace.

**Comment by malcolmsparks** [comment]
I know the CLJS support is very primitive right now, but my aim is to bring it up to par with lein-cljsbuild - I've done some work on the CLJS builder recently to allow it to discover ^:shared namespaces in the project classpath, in the same way as pedestal's app-tools. I'll add support for default-compiler-env too - I'll leave this issue open until that's done - thanks for this.

**Comment by malcolmsparks** [comment]
Ivan, this fix should have considerably speeded up the ClojureScript building process, haven't done any proper timings but this now feels much much faster, on par with lein-cljsbuild. Thanks very much for this suggestion, it's made my resets virtually instantaneous.
